sudo: required
language: ruby
rvm:
  - 2.2.5
addons:
  apt:
    packages:
      - oracle-java8-set-default
services:
  # - elasticsearch
  - mongodb
before_install:
  - gem install bundler -v 1.12.5
  -  apt-get update && sudo apt-get install elasticsearch
before_script:
  - sleep 10
